#!/bin/bash
# Quick Start Guide for New Features
# This file provides quick commands to test the new features

echo "============================================"
echo "Employee Management System - Quick Start"
echo "============================================"
echo ""

# Step 1: Start Backend
echo "Step 1: Starting Backend Server..."
echo "Run this command in a terminal:"
echo "  python backend_python/app.py"
echo ""
echo "Expected output:"
echo "  ✓ Initializing database..."
echo "  ✓ Database ready"
echo "  ✓ Server running on http://localhost:5001"
echo ""

# Step 2: Open Frontend
echo "Step 2: Opening Frontend Application..."
echo "Open this URL in your browser:"
echo "  http://localhost:8888"
echo ""

# Step 3: Login
echo "Step 3: Login with Admin Account"
echo "Email:    admin@company.com"
echo "Password: admin123"
echo ""

# Step 4: Test Features
echo "Step 4: Test New Features"
echo ""
echo "TEST 1: Login Attempt Tracking"
echo "  1. Logout from admin account"
echo "  2. Try to login 3 times with wrong password"
echo "  3. You'll see: ⚠️ WARNING message"
echo "  4. Try 2 more times (total 5)"
echo "  5. You'll see: 🔒 LOCKED for 30 seconds"
echo "  6. Login inputs will be disabled"
echo "  7. Wait 30 seconds, inputs re-enable"
echo ""

echo "TEST 2: Password Change Log"
echo "  1. Login as admin"
echo "  2. Scroll down to 'Password Change Log' table"
echo "  3. It shows all password changes (if any)"
echo "  4. You should see: User ID, Action, Changed By, Timestamp"
echo ""

echo "TEST 3: Soft Delete Employees"
echo "  1. Go to Employees table"
echo "  2. Click 'Delete' on any employee"
echo "  3. Confirm deletion"
echo "  4. Employee disappears from active list"
echo "  5. Scroll to 'Deleted Employees Archive' table"
echo "  6. Click 'Restore' to bring employee back"
echo ""

echo "TEST 4: Admin-Only Visibility"
echo "  1. Login as admin → See all tables (Employees, Users, Logs, Archive)"
echo "  2. Create a regular user (signup form)"
echo "  3. Login as regular user → See only Employees table"
echo "  4. Log all other tables are hidden for non-admin users"
echo ""

# Step 5: Monitor
echo "============================================"
echo "MONITORING NEW FEATURES"
echo "============================================"
echo ""
echo "Password Change Log:"
echo "  • See all password modifications"
echo "  • View admin who made changes"
echo "  • Check exact timestamps"
echo ""

echo "Login Attempts Log:"
echo "  • Monitor failed login attempts"
echo "  • Track IP addresses"
echo "  • See account lock status"
echo "  • Identify brute force attempts"
echo ""

echo "Deleted Employees Archive:"
echo "  • View all soft-deleted employees"
echo "  • See deletion history"
echo "  • Restore deleted employees"
echo "  • No data is permanently lost"
echo ""

# Step 6: Database Info
echo "============================================"
echo "DATABASE INFORMATION"
echo "============================================"
echo ""
echo "Location: backend_python/data/database.db"
echo ""
echo "New Tables Created:"
echo "  1. password_logs - Tracks password changes"
echo "  2. login_attempts - Tracks login attempts"
echo "  3. deleted_employees - Archive of deleted employees"
echo ""

# Step 7: Useful SQL Queries
echo "============================================"
echo "USEFUL DATABASE QUERIES"
echo "============================================"
echo ""
echo "View all failed login attempts:"
echo "  sqlite3 backend_python/data/database.db"
echo "  SELECT email, attempt_count, is_locked, last_attempt_time"
echo "  FROM login_attempts ORDER BY attempt_count DESC;"
echo ""

echo "View all password changes:"
echo "  SELECT user_id, changed_by_name, timestamp"
echo "  FROM password_logs ORDER BY timestamp DESC;"
echo ""

echo "View all deleted employees:"
echo "  SELECT first_name, last_name, deleted_by_name, deleted_at"
echo "  FROM deleted_employees ORDER BY deleted_at DESC;"
echo ""

echo "Reset a locked account (admin):"
echo "  UPDATE login_attempts SET is_locked = 0, attempt_count = 0"
echo "  WHERE email = 'user@example.com';"
echo ""

# Step 8: Troubleshooting
echo "============================================"
echo "TROUBLESHOOTING"
echo "============================================"
echo ""
echo "Backend won't start?"
echo "  • Check Python is installed: python --version"
echo "  • Install dependencies: pip install -r requirements.txt"
echo "  • Make sure port 5001 is not in use"
echo ""

echo "Frontend won't load?"
echo "  • Clear browser cache (Ctrl+Shift+Del)"
echo "  • Check if backend is running (should see no 'Failed to fetch' errors)"
echo "  • Try http://localhost:7777 or http://localhost:9000"
echo ""

echo "Database locked?"
echo "  • Stop backend (Ctrl+C)"
echo "  • Delete: backend_python/data/database.db"
echo "  • Restart backend (it will recreate database)"
echo ""

# Step 9: Key Files
echo "============================================"
echo "KEY FILES TO REVIEW"
echo "============================================"
echo ""
echo "Documentation:"
echo "  • COMPLETE_IMPLEMENTATION.md - Full overview"
echo "  • FEATURES_GUIDE.md - User guide"
echo "  • FEATURES_DIAGRAM.md - Visual diagrams"
echo "  • IMPLEMENTATION_SUMMARY.md - Technical details"
echo ""

echo "Code Files Modified:"
echo "  • backend_python/app.py - Backend logic"
echo "  • src/js/modules/logs.js - Log management"
echo "  • src/html/dashboard.html - Admin tables"
echo ""

# Step 10: Success
echo "============================================"
echo "✅ SETUP COMPLETE!"
echo "============================================"
echo ""
echo "All features are ready to use:"
echo "  ✓ Password Change Log"
echo "  ✓ Login Attempt Tracking with Cooldown"
echo "  ✓ Soft Delete with Archive & Restore"
echo ""
echo "Next steps:"
echo "  1. Start the backend server"
echo "  2. Open the frontend in your browser"
echo "  3. Test each feature following the guides above"
echo "  4. Review the documentation files"
echo ""
echo "For more information, see COMPLETE_IMPLEMENTATION.md"
echo ""
